export const bookmarks = [
  // EDUCATION
  { title: "Journey to Blockchain Engineer", url: "https://github.com/0xSmartContract/Journey-to-become-a-Blockchain-Engineer", category: "Education", desc: "A comprehensive roadmap for becoming a blockchain engineer." },
  { title: "Mastering Ethereum", url: "https://github.com/ethereumbook/ethereumbook", desc: "Fundamental book covering Ethereum architecture.", category: "Education" },
  { title: "Bug Bounty for Beginners", url: "https://github.com/nahamsec/Resources-for-Beginner-Bug-Bounty-Hunters", desc: "Essential resources for ethical hacking.", category: "Education" },
  { title: "CryptoZombies", url: "https://cryptozombies.io/", desc: "Interactive platform teaching smart contract development.", category: "Education" },
  { title: "Smart Contract Engineer", url: "https://www.smartcontract.engineer/", desc: "Modern smart contract engineering lessons.", category: "Education" },
  { title: "Web3 Security Library", url: "https://github.com/immunefi-team/Web3-Security-Library/tree/main/BugFixReviews", desc: "Immunefi's massive library of bug fixes.", category: "Education" },
  { title: "Solana Security Best Practices", url: "https://github.com/slowmist/solana-smart-contract-security-best-practices", desc: "SlowMist's guide for Solana security.", category: "Education" },
  { title: "Web3Sec Notion Hub", url: "https://web3sec.notion.site/c582b99cd7a84be48d972ca2126a2a1f", desc: "Hub for Web3 security documentation.", category: "Education" },
  { title: "DeFi Hacks Analysis - Root Cause", url: "https://wooded-meter-1d8.notion.site/0e85e02c5ed34df3855ea9f3ca40f53b?v=22e5e2c506ef4caeb40b4f78e23517ee", desc: "Hub for Web3 security documentation.", category: "Education" },
  { title: "Secureum", url: "https://secureum.xyz/", desc: "Educational bootcamp for audit training.", category: "Education" },
  { title: "SWC Registry", url: "https://swcregistry.io/", desc: "Smart Contract Weakness Classification.", category: "Education" },
  { title: "Speed Run Ethereum", url: "https://speedrunethereum.com/", desc: "Learn Solidity through interactive challenges.", category: "Education" },
  { title: "Ethernaut Level 0 Walkthrough", url: "https://medium.com/hackernoon/ethernaut-lvl-0-walkthrough-abis-web3-and-how-to-abuse-them-d92a8842d71b", desc: "Guide for Ethernaut mechanics and ABIs.", category: "Education" },
  { title: "Building Secure Smart Contracts", url: "https://secure-contracts.com/", desc: "Comprehensive guide on smart contract security.", category: "Education" },
  { title: "Audit Learning Short Roadmap", url: "https://rentry.co/wayofauditor", desc: "Roadmap for beginners covering documentation.", category: "Education" },
  { title: "Learn Me A Bitcoin Explorer", url: "https://learnmeabitcoin.com/explorer/", desc: "Educational Bitcoin blockchain explorer.", category: "Education" },
  { title: "The 0 to 1 Guide for MEV", url: "https://paragraph.com/@blockchainatberkeley/the-0-to-1-guide-for-mev", desc: "A quick and dirty guide to MEV by Blockchain at Berkeley.", category: "Education" },
  { title: "Smart Contract Vulnerabilities", url: "https://github.com/kadenzipfel/smart-contract-vulnerabilities", desc: "Detailed repository of smart contract vulnerabilities.", category: "Education" },
  { title: "Web3 Security Skills", url: "https://github.com/pashov/skills", desc: "Skills needed and resources for Web3 security auditing by Pashov.", category: "Education" },
  { title: "Smart Contract Hacking Course", url: "https://youtube.com/playlist?list=PLw50A09Og0Vt1nW_Csdo5XjrtHpRiBKo0&si=NjiYyISngS78wAWU", desc: "Video playlist for learning smart contract hacking.", category: "Education" },
  { title: "Web3 Security Talks & Content", url: "https://youtube.com/playlist?list=PLw50A09Og0VuKZSCqHPPiznIwdEERhDDd&si=eeRPH3TRGsktMask", desc: "Comprehensive video content covering Web3 security.", category: "Education" },
  { title: "Web3 Bug Bounty Videos", url: "https://youtube.com/playlist?list=PLCwnLq3tOElrubfUWHa1qKrJv1apO8Aag&si=iYgo0HhqwmRjhpcn", desc: "Playlist focusing on Web3 bug bounty content and writeups.", category: "Education" },
  { title: "DeFi Security Bootcamp", url: "https://youtube.com/playlist?list=PLKXasCp8iWphwMx-ZvXJc1VXK4HofzOLn&si=N6q723LfkP-pec0B", desc: "Bootcamp videos deep-diving into decentralized finance security.", category: "Education" },
  { title: "Intro to Smart Contract Auditing", url: "https://youtu.be/Ug5Vm-B7DNg?si=z87_xi630khqLb4w", desc: "Introduction to smart contract auditing basics.", category: "Education" },

  // AUDIT
  { title: "Spearbit Portfolio", url: "https://github.com/spearbit/portfolio/tree/master/pdfs", desc: "Professional audit reports by Spearbit.", category: "Audit" },
  { title: "Sherlock Audit Judging", url: "https://github.com/orgs/sherlock-audit/repositories", desc: "Sherlock audit competition archives.", category: "Audit" },
  { title: "OpenZeppelin Research", url: "https://www.openzeppelin.com/research", desc: "Security audit archives and research from industry leaders.", category: "Audit" },
  { title: "Yearn Security", url: "https://github.com/yearn/yearn-security", desc: "Security architecture of Yearn Finance.", category: "Audit" },
  { title: "HackerOne Web3 Reports", url: "https://github.com/reddelexc/hackerone-reports", desc: "Real Web3 vulnerability reports.", category: "Audit" },
  { title: "Awesome Bugbounty Writeups", url: "https://github.com/devanshbatham/Awesome-Bugbounty-Writeups", desc: "Curated list of high-quality writeups.", category: "Audit" },
  { title: "Disclosed Bug Reports", url: "https://github.com/marcotuliocnd/bugbounty-disclosed-reports", desc: "Archive of publicly disclosed reports.", category: "Audit" },
  { title: "QuillAudits Reports", url: "https://www.quillaudits.com/audit-reports", desc: "Extensive smart contract audit database.", category: "Audit" },
  { title: "Auditors 2022 Rewind", url: "https://ventral.digital/posts/2022/12/15/ethereum-smart-contract-auditors-2022-rewind/", desc: "Retrospective on smart contract auditing in 2022.", category: "Audit" },
  { title: "Block Audit Report", url: "https://blockauditreport.medium.com/", desc: "Collection of audit reports and findings.", category: "Audit" },
  { title: "DeFi Fork Bugs", url: "https://github.com/yAudit/defi-fork-bugs", desc: "Common bugs found in DeFi forks.", category: "Audit" },
  { title: "Ward Audits Portfolio", url: "https://github.com/WardAudits/portfolio?tab=readme-ov-file", desc: "Audits and findings by Ward Audits.", category: "Audit" },
  { title: "Pashov Audits", url: "https://github.com/pashov/audits", desc: "Collection of smart contract audits performed by Pashov.", category: "Audit" },

  // NEWS/ANALYSIS
  { title: "SlowMist Hacked", url: "https://hacked.slowmist.io/", desc: "Real-time tracking of crypto hacks.", category: "News/Analysis" },
  { title: "BlockThreat Intelligence", url: "https://newsletter.blockthreat.io/archive", desc: "Weekly newsletter covering Web3 threats.", category: "News/Analysis" },
  { title: "Deep DeFi Value", url: "https://deepfivalue.substack.com/", desc: "Deep dives into DeFi security risks.", category: "News/Analysis" },
  { title: "Misinfo Underload", url: "https://misinfounderload.substack.com/", desc: "Analysis of news and disinformation.", category: "News/Analysis" },
  { title: "Physical Bitcoin Attacks", url: "https://github.com/jlopp/physical-bitcoin-attacks", desc: "Records of physical attacks on owners.", category: "News/Analysis" },
  { title: "Rekt News", url: "https://rekt.news/", desc: "The dark side of DeFi, hacks and analysis.", category: "News/Analysis" },
  { title: "Web3 Is Going Great", url: "https://web3isgoinggreat.com/", desc: "Timeline of disasters in the web3 space.", category: "News/Analysis" },
  { title: "Anatomy of a Bitcoin Heist", url: "https://medium.com/@nbax/anatomy-of-a-bitcoin-heist-the-electrum-atom-malware-saga-1685abf7c903", desc: "Detailed analysis of the Electrum Atom malware saga.", category: "News/Analysis" },
  { title: "Insider Trading Hackers", url: "https://medium.com/@thinkermediayt/insider-trading-hackers-53ede4f31e5a", desc: "Investigation into insider trading and hacking.", category: "News/Analysis" },

  // RESEARCH
  { title: "Solidity Security Blog", url: "https://github.com/sigp/solidity-security-blog", desc: "Technical articles from Sigma Prime.", category: "Research" },
  { title: "QuillAudits Research", url: "https://quillaudits.medium.com/", desc: "Technical vulnerability analysis papers.", category: "Research" },
  { title: "cmichel.io", url: "https://cmichel.io/", desc: "Writeups from an independent researcher.", category: "Research" },
  { title: "SecurrTech Blog", url: "https://securrtech.medium.com/", desc: "Deep technical articles on security.", category: "Research" },
  { title: "Degatchi Research", url: "https://degatchi.com/", desc: "Writings on unconventional smart contracts.", category: "Research" },
  { title: "Immunefi Medium", url: "https://medium.com/immunefi", desc: "Post-mortems of major DeFi hacks.", category: "Research" },
  { title: "Samczsun's Blog", url: "https://samczsun.com/", desc: "Legendary whitehat hacker's research.", category: "Research" },
  { title: "Paradigm Research", url: "https://www.paradigm.xyz/writing", desc: "Top-tier crypto ecosystem research.", category: "Research" },
  { title: "Wallet Extension Pentesting", url: "https://blog.valkyri.xyz/posts/wallet-extension-pentesting/", desc: "Guide to pentesting crypto wallet extensions.", category: "Research" },
  { title: "SunSec Blog", url: "https://web3sec.notion.site/I-m-SunSec-ddaa8bf9a985494dbaf70d698345b899", desc: "Security notes and research by SunSec.", category: "Research" },
  { title: "Advanced Security Research", url: "https://tropical-comb-1dc.notion.site/b7df825e3f0f4278bb297b1eda576494?v=01376a29af164585a380840b02bb9dd3", desc: "Vulnerability research and deep dives.", category: "Research" },
  { title: "SlowMist Blog", url: "https://slowmist.medium.com/", desc: "Security insights and reports from SlowMist.", category: "Research" },
  { title: "Solidity Security: Known Attack Vectors", url: "https://blog.sigmaprime.io/solidity-security.html", desc: "Comprehensive list of known attack vectors and common anti-patterns.", category: "Research" },
  { title: "Weilin (William) Li's Blog", url: "https://weilinli.io/", desc: "Security researcher blog, publications, and bug bounties.", category: "Research" },
  { title: "AI in Web3 Security", url: "https://github.com/pashov/ai-web3-security", desc: "Resources on applying AI in Web3 security by Pashov.", category: "Research" },

  // LABS
  { title: "Damn Vulnerable DeFi", url: "https://www.damnvulnerabledefi.xyz/", desc: "The ultimate CTF for hacking DeFi.", category: "Labs" },
  { title: "Ethernaut OpenZeppelin", url: "https://ethernaut.openzeppelin.com/", desc: "Wargame to learn Web3 vulnerabilities.", category: "Labs" },
  { title: "Capture The Ether", url: "https://capturetheether.com/", desc: "Educational game for Ethereum security.", category: "Labs" },
  { title: "DeFi Vuln Labs", url: "https://github.com/SunWeb3Sec/DeFiVulnLabs", desc: "Educational laboratory for vulnerabilities.", category: "Labs" },
  { title: "DeFi Hack Labs", url: "https://github.com/SunWeb3Sec/DeFiHackLabs", desc: "Reproduced POCs for real-world hacks.", category: "Labs" },
  { title: "Salmonella", url: "https://github.com/Defi-Cartel/salmonella", desc: "PoC for sandwich trading exploits.", category: "Labs" },
  { title: "DeFi Labs", url: "https://github.com/SunWeb3Sec/DeFiLabs", desc: "Collection of DeFi security labs and experiments.", category: "Labs" },
  { title: "BlockSec CTFs", url: "https://github.com/blockthreat/blocksec-ctfs", desc: "Archive of blockchain security CTFs.", category: "Labs" },
  { title: "Some MEV Bots", url: "https://rentry.co/somemevbots", desc: "Collection of MEV bots and related resources.", category: "Labs" }
];
